[package]
name = "zymbol-repl"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Interactive REPL for Zymbol-Lang"

[dependencies]
zymbol-lexer.workspace = true
zymbol-parser.workspace = true
zymbol-interpreter.workspace = true
zymbol-error.workspace = true
zymbol-span.workspace = true
crossterm.workspace = true
arboard.workspace = true
unicode-width = "0.2"
dirs = "6"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
